import { test, expect } from './fixtures';
import type { Page } from '@playwright/test';
async function ready(page:Page){await page.goto('/');await page.waitForFunction(()=>!!(window as any).__mojian?.editor);await expect(page).toHaveTitle('墨笺 · Markdown 公众号排版');await expect(page.locator('vite-error-overlay')).toHaveCount(0);}
async function setDoc(page:Page,text:string){await page.evaluate(text=>(window as any).__mojian.setMarkdown(text),text);}
async function markdown(page:Page){return page.evaluate(()=>(window as any).__mojian.getMarkdown());}

test('editor image and Mermaid click previews zoom without changing Markdown, restore selection and close correctly',async({page})=>{
 test.setTimeout(60000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')errors.push(m.text());});await ready(page);
 const src=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=900;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#f4e9e5';ctx.fillRect(0,0,1600,900);ctx.fillStyle='#a6493d';ctx.font='60px sans-serif';ctx.fillText('Image preview',100,160);const blob=await new Promise<Blob>(r=>canvas.toBlob(b=>r(b!)));const {storeImage}=await import('/src/storage.ts');return storeImage(blob);});
 await setDoc(page,`# 预览测试\n\n![本地图](${src} "width=40%")\n\n\`\`\`mermaid\nflowchart LR\n编辑-->预览-->放大查看\n\`\`\``);const before=await markdown(page);
 await page.locator('.image-box img').click();const imageDialog=page.getByRole('dialog',{name:'图片预览',exact:true});await expect(imageDialog).toBeVisible();await expect(imageDialog.locator('img')).toBeVisible();await expect(imageDialog.locator('img')).toHaveAttribute('src',/^blob:/);await imageDialog.getByRole('button',{name:'放大预览',exact:true}).click();await expect(imageDialog.getByLabel('预览缩放比例')).toHaveValue(/^[0-9.]+$/);await imageDialog.getByRole('button',{name:'原始尺寸',exact:true}).click();await expect(imageDialog.getByLabel('预览缩放比例')).toHaveValue('100');expect(await imageDialog.locator('.media-preview-content img').evaluate(img=>Math.round(img.getBoundingClientRect().width))).toBe(1600);expect(await imageDialog.locator('.media-preview-viewport').evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(true);
 const ratio=imageDialog.getByRole('spinbutton',{name:'预览缩放比例',exact:true});
 await imageDialog.getByRole('button',{name:'放大预览',exact:true}).click();await expect(ratio).toHaveValue('110');await imageDialog.getByRole('button',{name:'缩小预览',exact:true}).click();await expect(ratio).toHaveValue('100');
 await ratio.fill('137.5');await ratio.press('Enter');await expect(ratio).toHaveValue('137.5');expect(await imageDialog.locator('img').evaluate(img=>Math.round(img.getBoundingClientRect().width))).toBe(2200);
 const view=imageDialog.locator('.media-preview-viewport');const bounds=await view.boundingBox();const point={x:bounds!.x+bounds!.width*.65,y:bounds!.y+bounds!.height*.6};
 const imagePoint=()=>imageDialog.locator('img').evaluate((img:HTMLImageElement,point)=>{const box=img.getBoundingClientRect();return {x:(point.x-box.left)*img.naturalWidth/box.width,y:(point.y-box.top)*img.naturalHeight/box.height};},point);
 const position=await imagePoint();await page.mouse.move(point.x,point.y);await page.mouse.wheel(0,-120);await expect.poll(async()=>Number(await ratio.inputValue())).toBeGreaterThan(137.5);const after=await imagePoint();expect(Math.abs(position.x-after.x)).toBeLessThan(1);expect(Math.abs(position.y-after.y)).toBeLessThan(1);
 const enlarged=Number(await ratio.inputValue());await page.mouse.wheel(0,120);await expect.poll(async()=>Number(await ratio.inputValue())).toBeLessThan(enlarged);
 const valid=await ratio.inputValue();await ratio.fill('401');await ratio.press('Enter');await expect(ratio).toHaveValue(valid);await expect(imageDialog.getByRole('alert')).toContainText('10%–400%');await ratio.fill('');await ratio.press('Enter');await expect(ratio).toHaveValue(valid);
 await ratio.fill('400');await ratio.press('Enter');await page.mouse.move(point.x,point.y);await page.mouse.wheel(0,-120);await expect(ratio).toHaveValue('400');await expect(imageDialog.getByRole('button',{name:'放大预览',exact:true})).toBeDisabled();
 await ratio.fill('10');await ratio.press('Tab');await page.mouse.move(point.x,point.y);await page.mouse.wheel(0,120);await expect(ratio).toHaveValue('10');await expect(imageDialog.getByRole('button',{name:'缩小预览',exact:true})).toBeDisabled();
 await imageDialog.getByRole('button',{name:'适应窗口',exact:true}).click();await expect(imageDialog.getByLabel('预览缩放比例')).toHaveValue(/^[0-9.]+$/);expect(await markdown(page)).toBe(before);await page.keyboard.press('Escape');await expect(imageDialog).toHaveCount(0);await expect(page.getByRole('spinbutton',{name:'图片宽度百分比'})).toBeVisible();await page.getByRole('spinbutton',{name:'图片宽度百分比'}).fill('50');await expect.poll(()=>markdown(page)).toContain('width=50%');
 await expect(page.locator('.diagram svg')).toBeVisible();const modified=await markdown(page);await page.getByRole('button',{name:'预览 Mermaid 图表',exact:true}).click();const graph=page.getByRole('dialog',{name:'图表预览',exact:true});await expect(graph.locator('img')).toBeVisible();expect(await graph.locator('img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);await page.screenshot({path:'/tmp/mojian-media-desktop.png'});
 await graph.getByRole('button',{name:'关闭弹窗'}).click();await expect(graph).toHaveCount(0);expect(await markdown(page)).toBe(modified);
 await page.getByRole('button',{name:'预览 Mermaid 图表',exact:true}).focus();await page.keyboard.press('Enter');await expect(graph).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'预览 Mermaid 图表',exact:true})).toBeFocused();
 await page.getByRole('button',{name:'展示代码',exact:true}).click();await expect(page.locator('.code-node pre')).toBeVisible();await expect(page.getByRole('button',{name:'预览 Mermaid 图表',exact:true})).toHaveCount(0);expect(await markdown(page)).toBe(modified);expect(errors).toEqual([]);
});

test('WeChat preview image and diagram open by click and keyboard on mobile; controls never enter copied HTML',async({page})=>{
 test.setTimeout(60000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);await setDoc(page,'# 点击预览\n\n![网络图片](https://raw.githubusercontent.com/github/explore/main/topics/markdown/markdown.png)\n\n```mermaid\nflowchart TD\n打开草稿-->编辑文章-->预览图表-->发布文章\n```');
 await page.getByRole('button',{name:'公众号预览',exact:true}).click();const paper=page.getByLabel('公众号排版正文', {exact:true});await expect(paper.locator('[data-media-preview=diagram] svg')).toBeVisible();const before=await markdown(page);
 await paper.getByRole('button',{name:'预览图片：网络图片',exact:true}).click();await expect(page.getByRole('dialog',{name:'图片预览'}).locator('img')).toBeVisible();await page.locator('.dialog-backdrop').click({position:{x:2,y:2}});await expect(page.getByRole('dialog')).toHaveCount(0);
 await paper.getByRole('button',{name:'预览 Mermaid 图表',exact:true}).focus();await page.keyboard.press('Space');const dialog=page.getByRole('dialog',{name:'图表预览',exact:true});await expect(dialog.locator('img')).toBeVisible();await page.keyboard.press('Tab');expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);
 await page.setViewportSize({width:390,height:844});await expect(dialog.locator('img')).toBeVisible();const bounds=await dialog.boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(390);expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(844);await dialog.getByRole('spinbutton',{name:'预览缩放比例'}).fill('125');await dialog.getByRole('spinbutton',{name:'预览缩放比例'}).press('Enter');await expect(dialog.getByRole('spinbutton',{name:'预览缩放比例'})).toHaveValue('125');await page.screenshot({path:'/tmp/mojian-media-mobile.png'});await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);
 expect(await markdown(page)).toBe(before);const html=await page.evaluate(()=>(window as any).__mojian.getOutput().html);expect(html).not.toContain('data-media-preview');expect(html).not.toContain('role="button"');expect(html).not.toContain('media-preview');expect(errors).toEqual([]);
});
